ethstorage/web3url-gateway

cmd/server/protocol.go
cmd/server/server_test.go

New query strings will be added at the end of URL to support the following case as in 
>https://0x4e1f41613c9084fdb9e34e11fae9412427480e56.w3eth.io/tokenSVG/1
to send 1 as a uint, and cast the result as SVG
```
mime.content=image/svg+xml
mime.type=svg
```
And if multiple args, priority is: type > content

support specifying mime type

---

cmd/server/protocol.go
cmd/server/server_test.go

In `manual` mode the undecoded path is sent as calldata to smart contracts.
In `auto` and `5219` mode we use URL decoded by HTTP request.

Handle URL decoding

---

cmd/server/autossl.go
cmd/server/helper.go
cmd/server/main.go
cmd/server/protocol.go
config.toml.sample

This help gateway  support the gateway custom domain name by [autocert](golang.org/x/crypto/acme/autocert). 
At first user should have the web3 deployed contract like : 
http://0xe15406f9092cb0cb77191fa3cbee92df07c9cc8b.80001.w3link.io/getMessage
Then add the Cname record as 
yourname.example.com ->  with value 0xe15406f9092cb0cb77191fa3cbee92df07c9cc8b.80001.w3link.io . 
At last visit  https://yourname.example.com .

custom domain support 

---

cmd/server/autossl.go

Fix issue: 
cannot access URLs that match the system certificate
Root cause: 
`filepath.WalkDir()` stops traversing the file in the configured system certificate path when an error is returned by the anonymous function, which causes the system certificate not to be loaded.
Solution:
return no error in the anonymous function of `filepath.WalkDir()`

fix no system cert loaded for new links

---

go.mod
go.sum

Hi!
This bump web3protocol-go at 0.2.3, which add support for [ERC-7618](https://github.com/ethereum/ERCs/pull/246) (Add Content-encoding handling in ERC-6944 resource request mode).
Test:
https://0xb464cac335daec57d4f50657ec846c3109c774b2.3334.w3link.io/gzip.js
will work as before, but the actual returned data will already be decompressed, and the HTTP header `Content-encoding: gzip` won't be sent to the client.
Also, unrelated to web3protocol-go, I saw the use of filepath.SkipAll which was introduced in go 1.20 so I bumped the value in go.mod.

Bump to web3protocol-go@0.2.3; Require go 1.20

---

cmd/server/protocol.go
config.toml.sample

Reason : The content-type could also have a prefix, such as `text/html; charset=utf-8`.
Also add es-t as a shortname.

HTML injection: Also handle content-type "text/html" with a suffix

---

cmd/server/protocol.go

Hi!
This PR improve the javascript patch in the following ways : 
- Fix the `web3://` to `https://` conversion when the A tag has elements inside (e.g. `<a><span>text</span></a>`)
- Now respect the `target`attribute of the A tag (`target="_blank"` open a new tab)
- Add support for altering the `src` attribute of IFRAME tags : convert from `web3://` to `https://`

Improve js patch

---

cmd/server/html.patch
cmd/server/protocol.go

Hi!
Sorry to request another PR just after the last one, but I believe this one should be the last : 
- It supports now all tags with a `src` attribute (so : iframe, img, audio, embed, script, ...)
- Fix: When processing inserted nodes, it will now also look at the children of the inserted node for web3:// urls in src attributes.
- As requested : I have moved the patch into a separate static file `html.patch`, which is loaded in go via the use of the `//go:embed html.patch` comment.

Improve HTML patch: All tags with src attributes are now covered.

---

cmd/server/html.patch

Hi!
Previously, for the Javascript patch: I used MutationObservers to transform web3:// links into https:// links in the src/href attribute.
These were not perfect, because the conversion code is executed **after** the element is inserted, so the element start to try to load the web3:// URL, and then right after it gets replaced.
It leads to some bad side effects such as : for Iframe, the user get a browser popup about handling web3:// links, and there are issues with loading <script> tags.
With this PR, I replace the use of MutationObservers by the use of attribute setter overrides, so that the URL is converted **before** the element is inserted into the document.
Thanks!

Javascript patch: src/href web3:// -> gateway convertor: Use setter override instead of MutationObservers

---

cmd/server/autossl.go

__Issue to address__
Error happens when trying to access https://0xb10fe009b82ed3319b4721b84e9ef64d5c5b52c9.11155111.web3gateway.dev
```
http: TLS handshake error from 103.121.208.149:57655: acme/autocert: missing certificate
```
It seems Autocert cannot get the certificate of the CA server when trying to create a new certificate.
__Caused by__
Privete key was not passed to `tls.X509KeyPair`
__Changes made__
Load private key from `KeyFile` defined in config.
__Tests__
https://0xb10fe009b82ed3319b4721b84e9ef64d5c5b52c9.11155111.web3gateway.dev works, as well as other link examples.

Fix "acme/autocert: missing certificate"

---

cmd/server/helper.go
cmd/server/main.go
cmd/server/protocol.go
config.toml.sample
go.mod
go.sum

Hi!
This PR add support for caching of 2 types.
The aim of caching is to reduce RPC calls to the RPC providers.
The first type of caching is easy : it is a config entry `pageCache.immutableUrlRegexps` in which we declare a list of URLs we know are immutable. So the first time a page is loaded from RPC, then the result is saved in cache, and will be served from cache for later calls.
The second type of caching is a partial implementation of standard proxy HTTP caching : If we visualize web3url-gateway being a proxy, and the web3protocol-go library being a remote server for which we proxy : we implement standard HTTP caching based on ETag.
The mechanism is basically : 
- Request arrive
- We check if we have it in cache
- If the request has no `If-None-Match` cache invalidation header, and …

Add cache support

---

cmd/server/protocol.go

Hi!
As discussed in last PR (https://github.com/ethstorage/web3url-gateway/pull/35 )
Now, in the cache clearing scenario: we no longer require a HTTP 200.
Scenario now covered : 
- Browser A request /path , web3protocol-go returns a body with an ETag, web3url-gateway caches it.
- Browser A request /path again, with If-None-Match, web3url-gateway forwards the call to web3protocol-go, which returns 304. The 304 is sent back to the browser.
- The owner of the website makes a modification : he now makes that /path return 404, because he wants to unpublish the page.
- - Browser A request /path again, with If-None-Match, web3url-gateway forwards the call to web3protocol-go, which returns 404 with no ETag. The cache is cleared in web3url-gateway, and the response is forwarded to browser.
This is …

Cache clearing scenario: Now cache clear for all non-304 HTTP code instead of only 200.

---

go.mod
go.sum

Hi!
Previously I added support for [ERC-7774](https://github.com/ethereum/ERCs/pull/652/files) with which a page can indicate that EVM events will be emitted when the page change.
I [have added](https://github.com/ethereum/ERCs/pull/652/commits/591aa10feabf9591c1b44096e79e40aab193a88f) in the ERC the possibility for a page to indicate that the EVM events can come from another contract that the one serving the page, and that the path argument it listen for could be different.
The reason : I expect a lot of "proxy" patterns, where a smartcontract will proxy pages from another contract.
Example: Someone publish an web3:// smart contract (e.g. a wallet app), and user can make their own versions by making a Simple proxy contract to the base app. Here, the user website page should listen for …

Bump web3protocol-go to v0.2.7

---

go.mod
go.sum

Hi!
In the context of the latest change regarding ERC-7774 and caching, this change optimize the RPC call usage in a low traffic situation.
Indeed, in order to track EVM events, it will regularly poll the blockchain for them. So roughly, if the traffic is no more than around 1 page view every 2 minutes, then the tracking system will cost more in RPC calls.
The solution, implemented in the new version, is simply to desactivate the tracking when there has been no use of the cache in the last XX minutes (here, put at 10).
So now, in case of traffic burst, caching will be active, and total RPC usage will be the tracker usage (1 call per 12s), and when there is no traffic, the cache tracker will be desactivated, and there will be no RPC usage.
Thanks!

Bump web3protocol-go to v0.2.8

---

go.mod
go.sum

Hi!
This fix the following reported issue by @0x_qz : After uninstalling an OCWebsite plugin, the pages were still cached.
Reason : The proposed ERC-7774 propose a cache clearing for the "*" path, so that all paths from a website is cleared. The contract was correctly emitting this on plugin uninstallation, but web3protocol-go had not implemented that yet.
Correction : The v0.2.9 version of web3protocol-go now implement the cache clearing for the "*" path.
Thanks!

Bump web3protocol-go to v0.2.9

---

go.mod
go.sum

Hi!
I have made a small change to web3protocol-go to make ERC-7774 caching handle temporary failure of RPC.
Demo : 
https://0x6dde8903cd77aacf07972ff44f7eac13d816e043.10.web3gateway.dev/
This website have an very large number of JS/CSS dependencies.
At first load, the site breaks, as only ~75% of assets loads, and then the RPC answers 429 Too many connections.
What we expect is that, since we have ERC-7774 caching, you load again, and it will only try to load the last 25% assets, and after one or two tries, it works fully. Then you can keep on refreshing the website, it will work, because everything is cached.
But right now it is not what is happens, what is happening now is : 
- A user loads https://0x6dde8903cd77aacf07972ff44f7eac13d816e043.10.web3gateway.dev/
- The RPC is overwhelmed, …

Bump web3protocol-go to v0.2.11

---

cmd/server/helper.go
cmd/server/main.go
cmd/server/protocol.go
cmd/server/sub_protocols.go
config.toml.sample
go.mod
go.sum

Hi!
This is a big one : 
- Now handling RPC 429 Too Many connections by waiting for them to be available again, with a timeout of 30s.
- A maximum number of concurrent requests are enforced per RPC
- There is the possibility to specify a "System RPC" per chain, different than the same one. This one is used for system worker (such as the ERC-7774 cache event checking), so that when the main RPC breaks, the one used by the workers still run. Much better, because if the ERC-7774 worker fails too long to make RPC calls, it clear all cache and desactivate itself.
- Multiple request for the same URL / specific HTTP headers are now grouped : if X person calls for the same thing, it will be processed only once.
- Fix an issue where, when the RPC was failing during resolve mode determination, it …

Bump web3protocol-go: Better graceful handling of 429, group processing of identical requests.

---

cmd/server/autossl.go
cmd/server/protocol.go

Addressing autocerts rate limits issue mentioned in https://github.com/ethstorage/web3url-gateway/issues/46.
Update on `GetCertificate()` to pre-check the server name by using `handleSubdomain()` to prevent continuous invalid URL requests.
Note: due to fmt issue, the only real change in `cmd/server/protocol.go`  is line 489, which fixes the index out of range.

Prevent DDoS on Autocert requests

---

cmd/server/helper.go
cmd/server/main.go
config.toml.sample
it/scripts/check-links.mjs

Addressing https://github.com/ethstorage/web3url-gateway/issues/55, this PR adds a middleware using semaphore to limit concurrent requests.
The default limit is 200 which can be configured in either config.toml or shell flag.
Tests have been done with `it/scripts/check-links.mjs`, showing that when `requestLimit` is set, the links that exceed the limit return 503: `Too many requests, please try again later.`

Limit concurrent requests

---

cmd/server/helper.go
cmd/server/html.patch
cmd/server/protocol.go
go.mod
go.sum

Hi!
These changes are here to help with web3:// integration in HTML pages with the gateway.
There is already some javascript injected to replace web3:// links, but after working with someone doing a web3:// website, we have found plenty of places where to improve that : 
- Added some extra javascript to handle more cases. The current javascript only work when specifically editing an attribute of a node, but it does not work with insertAdjacentHTML() inserting raw HTML.
- Fix insertion of the javascript patch : the `<body>` tag may have attributes. Right now it only expect `<body>` without attribute.
- Added direct edition of the HTML itself, when the web3:// links are directly in the HTML.
- Editing of the response Location HTTP header, when using 301/302 HTTP redirects.
- web3protocol-go …

Improved gateway integration in the HTML pages

---

.github/workflows/it.yml
cmd/server/protocol.go
it/scripts/check-links.mjs
it/scripts/index.js

Check links sequentially to lower the burden of the gateway server and RPCs, and retry bad links in case of temporary service unavailable.
Test results can be found [here](https://github.com/ethstorage/web3url-gateway/actions/runs/14968100815/job/42042585396).

Check links sequentially and retry bad links

---

cmd/server/html.patch
cmd/server/protocol.go

Hi!
Please consider this patch : this is more support for converting web3:// URLs at more places : 
- In javascript (via `node.innerHTML = 'xx'`) : add support for `<image href="">`, which is a tag used in `<svg>` tags.
- In javascript (via `insertAdjacentHTML('beforeend', xxx)` : Fix support for the root tag being inserted (conversion of `<div><img src="web3://xx"></div>` worked, but not `<img src="web3://xx">` without the wrapping `<div>`)
- In SVG files themselves : handle `<image href="">`
- In CSS files themselves, and in HTML : handle `url('')` (e.g. `background-image: url("web3://xxx");`)
Thanks for the reviewing!

More conversions of web3:// URLs into proxy HTTPS URLs

---

.github/workflows/it.yml

The action 'Check Links' has timed out after 10 minutes because the Sepolia transaction cannot be confirmed in time.
Extend the timeout setting to 30 minutes.

Fix timeout in 'check link` action
